apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx1
        image: nginx:latest
        ports:
          - containerPort: 80
      - name: nginx2
        image: nginx:latest
        ports:
          - containerPort: 8080
      initContainers:
      - name: initContainer
        image: initImage:latest