apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx1
          image: 111222333444.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:latest
          ports:
            - containerPort: 80
        - name: nginx2
          image: 111222333444.dkr.ecr.ap-northeast-1.amazonaws.com/nginx:latest
          ports:
            - containerPort: 8080
      initContainers:
        - name: initContainer
          image: 111222333444.dkr.ecr.ap-northeast-1.amazonaws.com/initImage:latest