apiVersion: v1
kind: Pod
metadata:
  name: static-web
  labels:
    role: myrole
spec:
  containers:
    - name: web
      image: 333222333444.dkr.ecr.ap-northeast-1.amazonaws.com/nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
  initContainers:
    - name: initContainer
      image: 333222333444.dkr.ecr.ap-northeast-1.amazonaws.com/initPod:v2.0.0
